/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.HoaDonController;
import Controller.KhachHangController;
import Controller.NhanVienController;
import Controller.SanPhamController;
import Model.HoaDonModel;
import Model.KhachHangModel;
import Model.NhanVienModel;
import Model.SanPhamModel;
import java.awt.Component;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author huyng
 */

public class HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form SanPham
     */
    public HoaDon(String maNhanVien) {
        initComponents();
        hienThiHoaDon();
        this.maNhanVien = maNhanVien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTHoaDon = new javax.swing.JTable();
        jBDuyet = new javax.swing.JButton();
        jBXoa = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jTHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá", "Số lượng", "Mã danh mục"
            }
        ));
        jScrollPane1.setViewportView(jTHoaDon);

        jBDuyet.setText("Duyệt");
        jBDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDuyetActionPerformed(evt);
            }
        });

        jBXoa.setText("Hủy");
        jBXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBDuyet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBXoa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDuyet)
                    .addComponent(jBXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private String maNhanVien;
    private void jBDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDuyetActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.jTHoaDon.getSelectedRow();

        // Kiểm tra nếu có hàng được chọn
        if (selectedRow != -1) {
            // Lấy dữ liệu ảnh từ hàng đã chọn
            String maHoaDon =  jTHoaDon.getValueAt(selectedRow, 0).toString(); 
            hdctl = new HoaDonController();
            HoaDonModel hd = new HoaDonModel();
            hd.setMaNhanVien(maNhanVien);
            hd.setMaHoaDon(maHoaDon);
            hdctl.suaHoaDon(hd);
            JOptionPane.showMessageDialog(this, "Duyệt thành công!");
            this.hienThiHoaDon();
        }
        else{
        JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần duyệt!");
        }
    }//GEN-LAST:event_jBDuyetActionPerformed
private KhachHangController khctl;
    private void jBXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoaActionPerformed
        // TODO add your handling code here:
int selectedRow = this.jTHoaDon.getSelectedRow();

// Kiểm tra nếu có hàng được chọn
if (selectedRow != -1) {
    // Lấy dữ liệu ảnh từ hàng đã chọn
    String maHoaDon = jTHoaDon.getValueAt(selectedRow, 0).toString();

    // Hiển thị JOptionPane xác nhận xóa
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn hủy hóa đơn này", "Xác nhận hủy", JOptionPane.YES_NO_OPTION);
    
    // Kiểm tra lựa chọn của người dùng
    if (confirm == JOptionPane.YES_OPTION) {
       hdctl = new HoaDonController();
       hdctl.xoaHoaDon(maHoaDon);
        JOptionPane.showMessageDialog(this, "Hủy đơn hàng thành công!");
        this.hienThiHoaDon();
    }
} else {
    JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần hủy cần xóa!");
}

    }//GEN-LAST:event_jBXoaActionPerformed
HoaDonController hdctl;
    public void hienThiHoaDon(){
    // Tạo mô hình dữ liệu cho jTSanPham
        DefaultTableModel tableModel = (DefaultTableModel) this.jTHoaDon.getModel();
        tableModel.setRowCount(0);
        tableModel.setColumnCount(0);
        tableModel.addColumn("Mã hóa đơn");
        tableModel.addColumn("Ngày lập");
        tableModel.addColumn("Tổng tiền");
        tableModel.addColumn("Mã khách hàng");
        tableModel.addColumn("Mã nhân viên");
        
         hdctl = new HoaDonController();
        // Gọi phương thức getListSanPham() để lấy danh sách sản phẩm
        List<HoaDonModel> hoaDonList = hdctl.getDanhSachHoaDon();

        // Duyệt qua danh sách sản phẩm và thêm từng sản phẩm vào mô hình dữ liệu
        for (HoaDonModel hoaDon : hoaDonList) {
            Object[] rowData = {
                hoaDon.getMaHoaDon(),
                hoaDon.getNgayLap(),
                hoaDon.getTongTien(),
                hoaDon.getMaKhachHang(),
                hoaDon.getMaNhanVien(),
            };
            tableModel.addRow(rowData);
            
}
// Đặt mô hình dữ liệu cho jTSanPham
jTHoaDon.setModel(tableModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDuyet;
    private javax.swing.JButton jBXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTHoaDon;
    // End of variables declaration//GEN-END:variables
}
