/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.KhachHangController;
import Controller.NhanVienController;
import Controller.SanPhamController;
import Controller.TaiKhoanController;
import Model.KhachHangModel;
import Model.NhanVienModel;
import Model.SanPhamModel;
import Model.TaiKhoanModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author huyng
 */
public class ThemSuaKhachHang extends javax.swing.JFrame {
    KhachHangController khctl;
    TaiKhoanController tkctl;
    /**
     * Creates new form ThemSuaChiTietSanPham
     */
    private int status;
    public ThemSuaKhachHang(){
     initComponents();
        CanGiua();
        layMaKhachHangTuDong();
         this.getContentPane().setBackground(new Color(98, 114, 164));
    }
    public ThemSuaKhachHang(KhachHang gdkh) {
        initComponents();
        CanGiua();
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        layMaKhachHangTuDong();
        this.status = 0;
        this.jTFMaKhachHang.setEditable(false);
        this.jLabel1.setText("Thêm khách hàng");
        this.gdkh = gdkh;
         this.getContentPane().setBackground(new Color(98, 114, 164));
    }
    public void layMaKhachHangTuDong(){
         khctl = new KhachHangController();
         this.jTFMaKhachHang.setText(khctl.getMaKhachHang());
       
    }
        public ThemSuaKhachHang(KhachHangModel kh, KhachHang gdkh) {
        initComponents();
        CanGiua();
        setThongTin(kh);
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        gdkh.hienThiKhachHang();
         this.jTFMaKhachHang.setEditable(false);
        this.status = 1;
        this.gdkh = gdkh;
         this.getContentPane().setBackground(new Color(98, 114, 164));
         this.jLabel1.setText("Sửa khách hàng");

    }
        public void setThongTin(KhachHangModel kh){
            this.jTFMaKhachHang.setText(kh.getMaKhachHang());
            this.jTFHoTen.setText(kh.getHoTen());
            this.jTFDiaChi.setText(kh.getDiaChi());
            this.jTFSoDienThoai.setText(kh.getSoDienThoai());
            this.jTFTenDangNhap.setText(kh.getTenDangNhap());
        }
  public void CanGiua(){
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int frameWidth = getWidth();
        int frameHeight = getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;
        setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFMaKhachHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBLuu = new javax.swing.JButton();
        jTFTenDangNhap = new javax.swing.JTextField();
        jTFSoDienThoai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPFMatKhau = new javax.swing.JPasswordField();
        jBDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm khách hàng");

        jLabel2.setText("Mã khách hàng:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Địa chỉ:");

        jLabel5.setText("Số điện thoại:");

        jLabel6.setText("Tên đăng nhập:");

        jBLuu.setText("Lưu");
        jBLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLuuActionPerformed(evt);
            }
        });

        jTFTenDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFTenDangNhapKeyTyped(evt);
            }
        });

        jTFSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSoDienThoaiKeyTyped(evt);
            }
        });

        jLabel7.setText("Mật khẩu:");

        jBDong.setText("Đóng");
        jBDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(jTFMaKhachHang, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFHoTen, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPFMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBLuu)
                                .addGap(18, 18, 18)
                                .addComponent(jBDong)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPFMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLuu)
                    .addComponent(jBDong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
private KhachHang gdkh = new KhachHang();
    private void jBLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLuuActionPerformed
        // TODO add your handling code here:
        khctl = new KhachHangController();
        if(this.status == 0){
        String maKhachHang = this.jTFMaKhachHang.getText();
        String tenNhanVien = this.jTFHoTen.getText();
        String diaChi = this.jTFDiaChi.getText();
        String soDienThoai = this.jTFSoDienThoai.getText();
        String tenDangNhap = this.jTFTenDangNhap.getText();
        String matKhau = this.jPFMatKhau.getText();
        
            TaiKhoanModel tk = new TaiKhoanModel(tenDangNhap, matKhau);
            tkctl = new TaiKhoanController();
            tkctl.themTaiKhoan(tk);
            KhachHangModel kh = new KhachHangModel(maKhachHang, tenNhanVien, diaChi, soDienThoai, tenDangNhap);
            khctl = new KhachHangController();
        khctl.themKhachHang(kh);
         JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
         this.dispose();
         gdkh.hienThiKhachHang();
        }

        else{
        String maKhachHang = this.jTFMaKhachHang.getText();
        String tenNhanVien = this.jTFHoTen.getText();
        String diaChi = this.jTFDiaChi.getText();
        String soDienThoai = this.jTFSoDienThoai.getText();
        String tenDangNhap = this.jTFTenDangNhap.getText();
                 KhachHangModel kh = new KhachHangModel(maKhachHang, tenNhanVien, diaChi, soDienThoai, tenDangNhap);
            khctl = new KhachHangController();
        khctl.suaKhachHang(kh);
         JOptionPane.showMessageDialog(this, "Sửa khách hàng thành công!");
         this.dispose();
         gdkh.hienThiKhachHang();
        }
    }//GEN-LAST:event_jBLuuActionPerformed

    private void jTFTenDangNhapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTenDangNhapKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTenDangNhapKeyTyped

    private void jTFSoDienThoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSoDienThoaiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSoDienThoaiKeyTyped

    private void jBDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBDongActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSuaKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDong;
    private javax.swing.JButton jBLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPFMatKhau;
    private javax.swing.JTextField jTFDiaChi;
    private javax.swing.JTextField jTFHoTen;
    private javax.swing.JTextField jTFMaKhachHang;
    private javax.swing.JTextField jTFSoDienThoai;
    private javax.swing.JTextField jTFTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
