/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SanPhamController;
import Model.SanPhamModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author huyng
 */
public class ThemSuaChiTietSanPham extends javax.swing.JFrame {
    SanPhamController spctl;
    /**
     * Creates new form ThemSuaChiTietSanPham
     */
   
    private int status;
    public ThemSuaChiTietSanPham(){
     initComponents();
        CanGiua();
        layMaSanPhamTuDong();
        this.getContentPane().setBackground(new Color(98, 114, 164));
    }
    public ThemSuaChiTietSanPham(SanPham gdsp) {
        initComponents();
        CanGiua();
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        layMaSanPhamTuDong();
         this.getContentPane().setBackground(new Color(98, 114, 164));
        this.status = 0;
        this.jTFMaSanPham.setEditable(false);
        this.jLabel1.setText("Thêm sản phẩm");
        this.gdsp = gdsp;
    }
    public void layMaSanPhamTuDong(){
         spctl = new SanPhamController();
         this.jTFMaSanPham.setText(spctl.getMaSanPham());
         this.jTFMaSanPham.setEditable(false);
       
    }
        public ThemSuaChiTietSanPham(SanPhamModel sp, SanPham gdsp) {
        initComponents();
        CanGiua();
        setAnh(sp);
         this.getContentPane().setBackground(new Color(98, 114, 164));
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
         this.jTFMaSanPham.setEditable(false);
        this.status = 1;
        this.gdsp = gdsp;
        this.jLabel1.setText("Sửa sản phẩm");

    }
        public void setAnh(SanPhamModel sp){
            this.jTFMaSanPham.setText(sp.getMaSanPham());
            this.jTFTenSanPham.setText(sp.getTenSanPham());
            this.jTFGia.setText(sp.getGia() + "");
            this.jSFSoLuong.setValue(sp.getSoLuong());
           this.jCBDanhMucSanPham.setSelectedItem(sp.getTenDanhMuc());
            image = sp.getAnh();
            byte[] imageBytes = sp.getAnh();
                    if (imageBytes != null) {
                // Tạo ImageIcon từ dữ liệu ảnh
                ImageIcon imageIcon = new ImageIcon(imageBytes);
        Image scaledImage = imageIcon.getImage().getScaledInstance(jLAnh.getWidth(), jLAnh.getHeight(), Image.SCALE_SMOOTH);
                    // Tạo ImageIcon từ ảnh đã được scale
                    ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                    // Gán ImageIcon vào JLabel
                    this.jLAnh.setIcon(scaledImageIcon);
            }
        
        }
  public void CanGiua(){
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int frameWidth = getWidth();
        int frameHeight = getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;
        setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFMaSanPham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFTenSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSFSoLuong = new com.toedter.components.JSpinField();
        jCBDanhMucSanPham = new javax.swing.JComboBox<>();
        jLAnh = new javax.swing.JLabel();
        jBChonAnh = new javax.swing.JButton();
        jBLuu = new javax.swing.JButton();
        jBDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi tiết sản phẩm");

        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setText("Tên sản phẩm:");

        jLabel4.setText("Giá:");

        jTFGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFGiaKeyTyped(evt);
            }
        });

        jLabel5.setText("Số lượng:");

        jLabel6.setText("Mã danh mục:");

        jSFSoLuong.setFocusCycleRoot(true);
        jSFSoLuong.setFocusable(false);
        jSFSoLuong.setMaximum(9999);
        jSFSoLuong.setMinimum(1);
        jSFSoLuong.setVerifyInputWhenFocusTarget(false);

        jCBDanhMucSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thời trang THOL", "Phụ kiện GYM THOL", "Shaker - Bình uống nước" }));

        jLAnh.setBackground(new java.awt.Color(204, 204, 204));
        jLAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAnh.setText("Ảnh");

        jBChonAnh.setText("Chọn ảnh");
        jBChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChonAnhActionPerformed(evt);
            }
        });

        jBLuu.setText("Lưu");
        jBLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLuuActionPerformed(evt);
            }
        });

        jBDong.setText("Đóng");
        jBDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSFSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTFTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTFMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTFGia, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBDanhMucSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBChonAnh)
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jBLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBDong))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSFSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBDanhMucSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBChonAnh)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLuu)
                    .addComponent(jBDong))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private byte[] image=  null;
    private void jBChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChonAnhActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
                fileChooser.setCurrentDirectory(new File("D:\\Project\\Java\\GymShop\\src\\main\\java\\Images"));
                // Chỉ cho phép chọn các file ảnh (định dạng: jpg, png, gif)
                FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image files", "jpg", "png", "gif");
                fileChooser.setFileFilter(imageFilter);
                int result = fileChooser.showOpenDialog(this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    // Đường dẫn tới file ảnh đã chọn
                    File selectedFile = fileChooser.getSelectedFile();
                    String imagePath = fileChooser.getSelectedFile().getAbsolutePath();
                    // Đọc dữ liệu từ file
Path path = Paths.get(imagePath);
byte[] imageData = null;
try {
    imageData = Files.readAllBytes(path);
    this.image = imageData;
} catch (IOException e) {
    e.printStackTrace();
}
                    // Tạo ImageIcon từ file ảnh
                    ImageIcon imageIcon = new ImageIcon(imagePath);
                    // Scale ảnh
                    Image scaledImage = imageIcon.getImage().getScaledInstance(jLAnh.getWidth(), jLAnh.getHeight(), Image.SCALE_SMOOTH);
                    // Tạo ImageIcon từ ảnh đã được scale
                    ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                    // Gán ImageIcon vào JLabel
                    this.jLAnh.setIcon(scaledImageIcon);
                    // Thực hiện xử lý file ảnh tại đây
                }
          
    }//GEN-LAST:event_jBChonAnhActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jTFGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFGiaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))){
        evt.consume();
        }
    }//GEN-LAST:event_jTFGiaKeyTyped
private SanPham gdsp = new SanPham();
    private void jBLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLuuActionPerformed
        // TODO add your handling code here:
        spctl = new SanPhamController();
        if(this.status == 0){
        String maSanPham = this.jTFMaSanPham.getText();
        String tenSanPham = this.jTFTenSanPham.getText();
        double gia = Double.parseDouble(this.jTFGia.getText());
        
        String tenDanhMuc = this.jCBDanhMucSanPham.getItemAt(this.jCBDanhMucSanPham.getSelectedIndex());
        int soLuong = this.jSFSoLuong.getValue();
        
        if(image != null){
            SanPhamModel sp = new SanPhamModel(maSanPham, tenSanPham, gia, soLuong,tenDanhMuc, image);
        spctl.themSanPham(sp);
         JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
         this.dispose();
         gdsp.hienThiSanPham();
        }
        else{
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ảnh!");
        }
        }
        else{
        String maSanPham = this.jTFMaSanPham.getText();
        String tenSanPham = this.jTFTenSanPham.getText();
        double gia = Double.parseDouble(this.jTFGia.getText());
        
        String tenDanhMuc = this.jCBDanhMucSanPham.getItemAt(this.jCBDanhMucSanPham.getSelectedIndex());
        int soLuong = this.jSFSoLuong.getValue();
        
        if(image != null){
            SanPhamModel sp = new SanPhamModel(maSanPham, tenSanPham, gia, soLuong,tenDanhMuc, image);
        spctl.suaSanPham(sp);
         JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công!");
         gdsp.hienThiSanPham();
         this.dispose();
        }
        else{
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ảnh!");
        }
        }
    }//GEN-LAST:event_jBLuuActionPerformed

    private void jBDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBDongActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSuaChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSuaChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSuaChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSuaChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSuaChiTietSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBChonAnh;
    private javax.swing.JButton jBDong;
    private javax.swing.JButton jBLuu;
    private javax.swing.JComboBox<String> jCBDanhMucSanPham;
    private javax.swing.JLabel jLAnh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.components.JSpinField jSFSoLuong;
    private javax.swing.JTextField jTFGia;
    private javax.swing.JTextField jTFMaSanPham;
    private javax.swing.JTextField jTFTenSanPham;
    // End of variables declaration//GEN-END:variables
}
